language: python

matrix:
  include:
    - python: 3.7
    - python: 3.8
  dist: bionic
  sudo: true

install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv install

script:
  - pipenv run pylint minesweeper/
  - pipenv run flake8 minesweeper/
  - pipenv run python -m pytest test/